### ISSUE TITLE
How to disable auto-update to load faster (might also have another issue)

### ISSUE THREAD

**Issue by Lucaspec72** [hylian-modding/ModLoader64-GUI#20]
I've read in a closed issue that the long loading time can be caused by poor internet speed, and my internet is VERY bad. Unfortunately i didn't find any "auto update" setting in the config file. where can i disable it ? (for context modloader started once, and now the loading window just shows up, closes, then shows up again, idk if it's bugged or really slow but it's annoying, this might be because of my internet speed though... also it always closes on "updating launcher")

Edit: Closing the program while it's loading in this state gives me the following error 

Unhandled Error
Error: Object has been destroyed
    at WebContents../lib/browser/api/web-contents.js.WebContents.send (electron/js2c/browser_init.js:3606:15)
    at MessageLayer.send (C:/Users/Lucas/Desktop/oot online/resources/app/MessageLayer.js:17:35)
    at ChildProcess.<anonymous> (C:/Users/Lucas/Desktop/oot online/resources/app/index.js:277:40)

idk if it's useful for solving my issue but i might as well include that just in case

**Comment by denoflionsx** [comment]
Make sure you're checking the correct config file. ModLoader64-GUI-config.json.

You probably have a bad update file because your internet won't stay stable long enough to complete the process. Should they exist delete app.pak, ModLoader.pak, and update.json.

The update process must complete or you'll be unable to connect to any ModLoader server.

**Comment by Lucaspec72** [comment]
thanks, turns out the update files where corrupted or something like that, deleting the files you mentioned fixed the issue. Thanks !
